-- Generated by Mocodo 4.3.2

CREATE TABLE ACTIVITY (
  PRIMARY KEY (activity_id),
  activity_id    VARCHAR(42) NOT NULL,
  title          VARCHAR(42),
  type           VARCHAR(42),
  sequence       VARCHAR(42),
  content        VARCHAR(42),
  pass_threshold VARCHAR(42),
  course_id      VARCHAR(42) NOT NULL
);

CREATE TABLE ANSWER (
  PRIMARY KEY (answer_id),
  answer_id   VARCHAR(42) NOT NULL,
  content     VARCHAR(42),
  is_correct  VARCHAR(42),
  question_id VARCHAR(42) NOT NULL
);

CREATE TABLE COMPETENCE (
  PRIMARY KEY (competence_id),
  competence_id VARCHAR(42) NOT NULL,
  name          VARCHAR(42),
  description   VARCHAR(42)
);

CREATE TABLE completes (
  PRIMARY KEY (employee_id, activity_id),
  employee_id  VARCHAR(42) NOT NULL,
  activity_id  VARCHAR(42) NOT NULL,
  completed_at VARCHAR(42)
);

CREATE TABLE COURSE (
  PRIMARY KEY (course_id),
  course_id       VARCHAR(42) NOT NULL,
  title           VARCHAR(42),
  description     VARCHAR(42),
  theme           VARCHAR(42),
  validity_months VARCHAR(42)
);

CREATE TABLE EMPLOYEE (
  PRIMARY KEY (employee_id),
  employee_id VARCHAR(42) NOT NULL,
  last_name   VARCHAR(42),
  first_name  VARCHAR(42),
  role_id     VARCHAR(42) NOT NULL
);

CREATE TABLE owns (
  PRIMARY KEY (competence_id, employee_id),
  competence_id VARCHAR(42) NOT NULL,
  employee_id   VARCHAR(42) NOT NULL
);

CREATE TABLE prerequisites (
  PRIMARY KEY (course_id_1, course_id_2),
  course_id_1 VARCHAR(42) NOT NULL,
  course_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE provides (
  PRIMARY KEY (competence_id, course_id),
  competence_id VARCHAR(42) NOT NULL,
  course_id     VARCHAR(42) NOT NULL
);

CREATE TABLE QUESTION (
  PRIMARY KEY (question_id),
  question_id VARCHAR(42) NOT NULL,
  statement   VARCHAR(42),
  activity_id VARCHAR(42) NOT NULL
);

CREATE TABLE ROLE (
  PRIMARY KEY (role_id),
  role_id VARCHAR(42) NOT NULL,
  title   VARCHAR(42)
);

CREATE TABLE role_requires (
  PRIMARY KEY (role_id, competence_id),
  role_id       VARCHAR(42) NOT NULL,
  competence_id VARCHAR(42) NOT NULL
);

CREATE TABLE subscribes_to (
  PRIMARY KEY (employee_id, course_id),
  employee_id        VARCHAR(42) NOT NULL,
  course_id          VARCHAR(42) NOT NULL,
  status             VARCHAR(42),
  certification_date VARCHAR(42)
);

ALTER TABLE ACTIVITY ADD FOREIGN KEY (course_id) REFERENCES COURSE (course_id);

ALTER TABLE ANSWER ADD FOREIGN KEY (question_id) REFERENCES QUESTION (question_id);

ALTER TABLE completes ADD FOREIGN KEY (activity_id) REFERENCES ACTIVITY (activity_id);
ALTER TABLE completes ADD FOREIGN KEY (employee_id) REFERENCES EMPLOYEE (employee_id);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (role_id) REFERENCES ROLE (role_id);

ALTER TABLE owns ADD FOREIGN KEY (employee_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE owns ADD FOREIGN KEY (competence_id) REFERENCES COMPETENCE (competence_id);

ALTER TABLE prerequisites ADD FOREIGN KEY (course_id_2) REFERENCES COURSE (course_id);
ALTER TABLE prerequisites ADD FOREIGN KEY (course_id_1) REFERENCES COURSE (course_id);

ALTER TABLE provides ADD FOREIGN KEY (course_id) REFERENCES COURSE (course_id);
ALTER TABLE provides ADD FOREIGN KEY (competence_id) REFERENCES COMPETENCE (competence_id);

ALTER TABLE QUESTION ADD FOREIGN KEY (activity_id) REFERENCES ACTIVITY (activity_id);

ALTER TABLE role_requires ADD FOREIGN KEY (competence_id) REFERENCES COMPETENCE (competence_id);
ALTER TABLE role_requires ADD FOREIGN KEY (role_id) REFERENCES ROLE (role_id);

ALTER TABLE subscribes_to ADD FOREIGN KEY (course_id) REFERENCES COURSE (course_id);
ALTER TABLE subscribes_to ADD FOREIGN KEY (employee_id) REFERENCES EMPLOYEE (employee_id);
